from module_constants import *
from ID_factions import *
from header_items import  *
from header_operations import *
from header_triggers import *

####################################################################################################################
#  Each item record contains the following fields:
#  1) Item id: used for referencing items in other files.
#     The prefix  is automatically added before each item id.
#  2) Item name. Name of item as it'll appear in inventory window
#  3) List of meshes.  Each mesh record is a tuple containing the following fields:
#    3.1) Mesh name.
#    3.2) Modifier bits that this mesh matches.
#     Note that the first mesh record is the default.
#  4) Item flags. See header_items.py for a list of available flags.
#  5) Item capabilities. Used for which animations this item is used with. See header_items.py for a list of available flags.
#  6) Item value.
#  7) Item stats: Bitwise-or of various stats about the item such as:
#      weight, abundance, difficulty, head_armor, body_armor,leg_armor, etc...
#  8) Modifier bits: Modifiers that can be applied to this item.
#  9) [Optional] Triggers: List of simple triggers to be associated with the item.
#  10) [Optional] Factions: List of factions that item can be found as merchandise.
####################################################################################################################

# Some constants for ease of use.
imodbits_none = 0
imodbits_horse_basic = imodbit_swaybacked|imodbit_lame|imodbit_spirited|imodbit_heavy|imodbit_stubborn
imodbits_cloth  = imodbit_tattered | imodbit_ragged | imodbit_sturdy | imodbit_thick | imodbit_hardened
imodbits_armor  = imodbit_rusty | imodbit_battered | imodbit_crude | imodbit_thick | imodbit_reinforced |imodbit_lordly
imodbits_plate  = imodbit_cracked | imodbit_rusty | imodbit_battered | imodbit_crude | imodbit_thick | imodbit_reinforced |imodbit_lordly
imodbits_polearm = imodbit_cracked | imodbit_bent | imodbit_balanced
imodbits_shield  = imodbit_cracked | imodbit_battered |imodbit_thick | imodbit_reinforced
imodbits_sword   = imodbit_rusty | imodbit_chipped | imodbit_balanced |imodbit_tempered
imodbits_sword_high   = imodbit_rusty | imodbit_chipped | imodbit_balanced |imodbit_tempered|imodbit_masterwork
imodbits_axe   = imodbit_rusty | imodbit_chipped | imodbit_heavy
imodbits_mace   = imodbit_rusty | imodbit_chipped | imodbit_heavy
imodbits_pick   = imodbit_rusty | imodbit_chipped | imodbit_balanced | imodbit_heavy
imodbits_bow = imodbit_cracked | imodbit_bent | imodbit_strong |imodbit_masterwork
imodbits_crossbow = imodbit_cracked | imodbit_bent | imodbit_masterwork
imodbits_missile   = imodbit_bent | imodbit_large_bag
imodbits_thrown   = imodbit_bent | imodbit_heavy| imodbit_balanced| imodbit_large_bag
imodbits_thrown_minus_heavy = imodbit_bent | imodbit_balanced| imodbit_large_bag

imodbits_horse_good = imodbit_spirited|imodbit_heavy
imodbits_good   = imodbit_sturdy | imodbit_thick | imodbit_hardened | imodbit_reinforced
imodbits_bad    = imodbit_rusty | imodbit_chipped | imodbit_tattered | imodbit_ragged | imodbit_cracked | imodbit_bent
# Replace winged mace/spiked mace with: Flanged mace / Knobbed mace?
# Fauchard (majowski glaive)

items = [
	["2full_plate_armor", "Plate_Armor", [("2full_plate_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield|itp_next_item_as_melee, 0, 2900, weight(24.0)|body_armor(55)|leg_armor(20)|difficulty(8), imodbits_cloth],
	["2great_helmet", "Great_Helmet", [("2great_helmet_new", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(53)|difficulty(10), imodbits_plate],
	["2kettle_hat_new", "Great_Helmet", [("2kettle_hat_new", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["asmoday_helmet2", "Helmet", [("asmoday_helmet2", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["assassin_helmet", "Assassin_Helm", [("assassin_helmet", 0)], itp_type_head_armor|itp_merchandise|itp_offset_lance, 0, 854, weight(2.75)|head_armor(49)|difficulty(9), imodbits_plate],
	["assassin_helmet2", "Assassin_Helm", [("assassin_helmet2", 0)], itp_type_head_armor|itp_merchandise|itp_offset_lance, 0, 854, weight(2.75)|head_armor(49)|difficulty(9), imodbits_plate],
	["bear_boots", "Bear_Boots", [("bear_boots", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 2360, weight(3.5)|leg_armor(35), imodbits_armor],
	["bear_warrior", "White_Bear_Armor", [("bear_warrior", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield|itp_next_item_as_melee, 0, 2900, weight(24.0)|body_armor(55)|leg_armor(20)|difficulty(8), imodbits_cloth],
	["bear_helmet_white", "White_Bear_Head", [("bear_warior_helm", 0)], itp_type_head_armor|itp_merchandise, 0, 500, weight(2.0)|head_armor(41)|difficulty(7), imodbits_plate],
	["beargauntlets", "Gauntlets", [("beargauntlets_L", 0), ("beargauntlets_L", imodbit_reinforced)], itp_type_hand_armor|itp_merchandise, 0, 1500, weight(1.0)|body_armor(6), imodbits_armor],
	["dark_lord_armor", "Dark_Lord_Armor", [("dark_lord_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 25295, weight(22.0)|head_armor(2)|body_armor(64)|leg_armor(25)|difficulty(30), imodbits_armor],
	["dark_lord_armor2", "Dark_Lord_Armor", [("dark_lord_armor2", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 25295, weight(22.0)|head_armor(2)|body_armor(64)|leg_armor(25)|difficulty(30), imodbits_armor],
	["demon_hood", "Asmoday's_Helmet", [("demon_hood", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["demonrobe", "Robe", [("demonrobe", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield|itp_next_item_as_melee, 0, 31, weight(1.5)|body_armor(8)|leg_armor(6), imodbits_cloth],
	["fix_black_armor", "Black_Armor", [("fix_black_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 6553, weight(27.0)|body_armor(55)|leg_armor(17)|difficulty(9), imodbits_plate],
	["g_helm_spak2", "Helmet", [("g_helm_spak2", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["g_iron_greaves_a", "Iron_Greaves", [("g_iron_greaves_a", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1770, weight(3.5)|leg_armor(33)|difficulty(9), imodbits_armor],
	["g_mail_boots_a", "Mail_Boots", [("g_mail_boots_a", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1, weight(3.0)|leg_armor(1), imodbits_armor],
	["g_mail_chausses_a", "Mail_Chausses", [("g_mail_chausses_a", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 530, weight(3.0)|leg_armor(24), imodbits_armor],
	["g_reinf_jerkin", "Rider_Armor", [("g_reinf_jerkin", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 2910, weight(27.0)|body_armor(52)|leg_armor(14)|difficulty(9), imodbits_armor],
	["g_scale_gauntlets_a", "Lamellar_Gauntlets", [("g_scale_gauntlets_a_L", 0)], itp_type_hand_armor|itp_merchandise, 0, 910, weight(0.75)|body_armor(6), imodbits_armor],
	["g_tabard_a", "Demonic_Tabard", [("g_tabard_a", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield|itp_next_item_as_melee, 0, 307, weight(7.0)|body_armor(19)|leg_armor(6), imodbits_armor],
	["glowing_armor", "Glowing_Armor", [("glowing_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 10000, weight(28.0)|head_armor(2)|body_armor(64)|leg_armor(25)|difficulty(10), imodbits_plate|imodbit_hardened],
	["glowing_helmet", "Glowing_Helmet", [("glowing_helmet", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["plate_boots3", "Plate_Boots", [("plate_boots3", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1770, weight(3.5)|leg_armor(33)|difficulty(9), imodbits_plate],
	["scullhead4", "Helmet", [("scullhead4", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(50)|body_armor(1)|difficulty(10), imodbits_plate],
	["sp_helm1", "Helmet", [("sp_helm1", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["spak_black_armor", "Imperial_Armor", [("spak_black_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield|itp_next_item_as_melee, 0, 2900, weight(24.0)|body_armor(55)|leg_armor(20)|difficulty(8), imodbits_cloth],
	["spak_black_boots", "Plate_Boots", [("spak_black_boots", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1770, weight(3.5)|leg_armor(33)|difficulty(9), imodbits_plate],
	["spak_black_gauntlets", "Gauntlets", [("spak_black_gauntlets_L", 0), ("spak_black_gauntlets_L", imodbit_reinforced)], itp_type_hand_armor|itp_merchandise, 0, 1040, weight(1.0)|body_armor(6), imodbits_armor],
	["spak_coat_of_plates_a", "Coat_of_Plates", [("spak_coat_of_plates_a", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 4190, weight(28.0)|head_armor(2)|body_armor(53)|leg_armor(16)|difficulty(10), imodbits_armor],
	["spak_coat_of_plates_b", "Coat_of_Plates", [("spak_coat_of_plates_b", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 4050, weight(29.0)|body_armor(53)|leg_armor(16)|difficulty(10), imodbits_armor],
	["spak_coat_of_plates_d", "Coat_of_Plates", [("spak_coat_of_plates_d", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 4190, weight(28.0)|head_armor(2)|body_armor(53)|leg_armor(16)|difficulty(10), imodbits_armor],
	["spak_coat_of_plates_e", "Coat_of_Plates", [("spak_coat_of_plates_e", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 4300, weight(29.0)|head_armor(3)|body_armor(53)|leg_armor(16)|difficulty(10), imodbits_armor],
	["spak_coat_of_plates_f", "Coat_of_Plates", [("spak_coat_of_plates_f", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 4100, weight(28.0)|body_armor(53)|leg_armor(16)|difficulty(10), imodbits_armor],
	["spak_helmet_k", "Full_Helm", [("spak_helmet_k", 0)], itp_type_head_armor|itp_covers_head|itp_merchandise, 0, 811, weight(2.5)|head_armor(51)|difficulty(10), imodbits_plate],
	["spak_helmet_k2", "Full_Helm", [("spak_helmet_k2", 0)], itp_type_head_armor|itp_covers_head|itp_merchandise, 0, 811, weight(2.5)|head_armor(51)|difficulty(10), imodbits_plate],
	["sub_helm", "Helmet", [("sub_helm", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["sub_helm2", "Helmet", [("sub_helm2", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["sub_helm3", "Helmet", [("sub_helm3", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["sub_helm4", "Helmet", [("sub_helm4", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["twiligh_armor", "Twiligh_Armor", [("twiligh_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 25295, weight(22.0)|body_armor(64)|leg_armor(25)|difficulty(30), imodbits_armor],
	["twilight_boots", "Twilight_Boots", [("twilight_boots", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1770, weight(3.5)|leg_armor(33)|difficulty(9), imodbits_plate],
	["twilight_gloves", "Twilight_Gloves", [("twilight_gloves_L", 0), ("twilight_gloves_L", imodbit_reinforced)], itp_type_hand_armor|itp_merchandise, 0, 1500, weight(1.0)|body_armor(9), imodbit_crude|imodbit_reinforced|imodbit_lordly|imodbit_thick],
	["twilight_helm", "Twilight_Helmet", [("twilighthelm", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["twilight_helm2", "Twilight_Helmet", [("twilighthelm2", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["wolf_helm1", "Wolf_Helmet", [("wolf_helm1", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["wolf_helm2", "Wolf_Helmet", [("wolf_helm2", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(50)|difficulty(10), imodbits_plate],
	["wolf_helm3", "Wolf_Helmet", [("wolf_helm3", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["wolf_helm4", "Wolf_Helmet", [("wolf_helm4", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(50)|difficulty(10), imodbits_plate],
	["elite_cavalary", "Wolf_Armor", [("elite_cavalary", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 1800, weight(28.0)|body_armor(50)|leg_armor(22)|difficulty(9), imodbits_armor],
	["elite_cavalary_coif", "Wolf_Coif", [("elite_cavalary_coif", 0), ("elite_cavalary_coif_ixmesh_inv", ixmesh_carry)], itp_type_head_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_covers_beard|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 171, weight(1.25)|head_armor(25)|body_armor(1)|difficulty(7), imodbits_armor],
	["splate_armor", "Rusty_Armor", [("splate_armor", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 6553, weight(27.0)|body_armor(55)|leg_armor(17)|difficulty(9), imodbits_plate],
	["splate_armor2", "Rusty_Armor", [("splate_armor2", 0)], itp_type_body_armor|itp_merchandise|itp_can_penetrate_shield, 0, 6553, weight(27.0)|body_armor(55)|leg_armor(17)|difficulty(9), imodbits_plate],
	["helm07", "Horned_Helmet", [("helm07", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|body_armor(2)|difficulty(10), imodbits_plate],
	["demonic_gauntlets", "Demonic_Gloves", [("demonic_gauntlets_L", 0), ("demonic_gauntlets_L", imodbit_reinforced)], itp_type_hand_armor|itp_merchandise, 0, 1500, weight(1.0)|body_armor(9), imodbit_crude|imodbit_reinforced|imodbit_lordly|imodbit_thick],
	["demonic_boots", "Demonic_Boots", [("demonic_boots", 0)], itp_type_foot_armor|itp_attachment_mask|itp_force_attach_left_hand|itp_force_attach_right_hand|itp_force_attach_left_forearm|itp_merchandise, 0, 1770, weight(3.5)|leg_armor(33)|difficulty(9), imodbits_plate],
	["helmet_enforser", "Helmet", [("helmet_enforser", 0)], itp_type_head_armor|itp_merchandise, 0, 980, weight(2.75)|head_armor(55)|difficulty(10), imodbits_plate],
	["1steel_arrow", "Arrows", [("1steel_arrow", 0), ("flying_missile", ixmesh_carry), ("1steel_quiver", ixmesh_carry), ("1steel_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_quiver_back, 2000, weight(3.5)|weapon_length(95)|max_ammo(30)|thrust_damage(8, pierce), imodbits_missile],
	["2steel_arrow", "Steel_Arrows", [("2steel_arrow", 0), ("flying_missile", ixmesh_carry), ("2steel_quiver", ixmesh_carry), ("2steel_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_quiver_back, 2000, weight(3.5)|weapon_length(95)|max_ammo(30)|thrust_damage(8, pierce), imodbits_missile],
	["amazon_arrow", "Arrows", [("amazon_arrow", 0), ("flying_missile", ixmesh_carry), ("amazon_quiver", ixmesh_carry), ("amazon_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 1000, weight(3.5)|weapon_length(95)|max_ammo(60)|thrust_damage(5, pierce), imodbits_missile],
	["amazon_bow", "Short_Bow", [("amazon_bow", 0), ("amazon_bow_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 269, weight(1.25)|difficulty(3)|spd_rtng(90)|shoot_speed(57)|thrust_damage(21, pierce), imodbits_bow],
	["evil_arrow", "Evil_Arrows", [("evil_arrow", 0), ("evil_arrow_fl", ixmesh_carry), ("necronomicon", ixmesh_carry), ("necronomicon", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_sword_left_hip, 2000, weight(1.0)|weapon_length(95)|max_ammo(50)|thrust_damage(8, pierce), imodbits_none],
	["gromitearrow", "Arrows", [("gromitearrow", 0), ("flying_missile", ixmesh_carry), ("gromiteq", ixmesh_carry), ("gromiteq", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 1000, weight(3.5)|weapon_length(95)|max_ammo(100)|thrust_damage(4, pierce), imodbits_missile],
	["holy_bible", "Holy_Arrows", [("holy_arrow", 0), ("holy_arrow_fl", ixmesh_carry), ("holy_bible", ixmesh_carry), ("holy_bible", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_sword_left_hip, 2000, weight(1.0)|weapon_length(95)|max_ammo(50)|thrust_damage(8, pierce), imodbits_none],
	["imperial_bow", "Imperial_Bow", [("imperial_bow", 0), ("imperial_bow_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 1961, weight(1.25)|spd_rtng(124)|shoot_speed(98)|thrust_damage(80, pierce), imodbits_bow|imodbit_balanced|imodbit_crude],
	["lonely", "Bow", [("lonely", 0), ("lonely_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 17962, weight(1.25)|body_armor(32)|leg_armor(92)|difficulty(3)|spd_rtng(94)|shoot_speed(75)|thrust_damage(38, pierce), imodbits_crossbow],
	["lonely_ar", "Arrows", [("lonely_ar", 0), ("flying_missile", ixmesh_carry), ("lonely_quiver", ixmesh_carry), ("lonely_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(60)|thrust_damage(8, pierce), imodbits_missile],
	["new1_arrow", "Arrows", [("new1_arrow", 0), ("flying_missile", ixmesh_carry), ("new1", ixmesh_carry), ("new1", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["noldor_bow", "Noldor_Bow", [("noldor_bow", 0), ("noldor_bow_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 7961, weight(1.25)|leg_armor(95)|difficulty(6)|spd_rtng(94)|shoot_speed(92)|thrust_damage(32, pierce), imodbits_crossbow],
	["scorm_bow", "Scorm's_Bow", [("scorm", 0), ("scorm_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 7654, weight(2.0)|leg_armor(99)|spd_rtng(125)|shoot_speed(98)|thrust_damage(82, pierce), imodbits_bow|imodbit_balanced],
	["skull_arrow", "Arrows", [("skull_arrow", 0), ("flying_missile", ixmesh_carry), ("skull_quiver", ixmesh_carry), ("skull_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 1000, weight(3.5)|weapon_length(95)|max_ammo(60)|thrust_damage(5, pierce), imodbits_missile],
	["short_imperial_bow", "Imperial_Short_Bow", [("short_imperial_bow", 0), ("short_imperial_bow_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 7961, weight(1.25)|leg_armor(95)|difficulty(6)|spd_rtng(94)|shoot_speed(92)|thrust_damage(32, pierce), imodbits_crossbow],
	["skeleton_archer_arrow", "Arrows", [("skeleton_archer_arrow", 0), ("flying_missile", ixmesh_carry), ("skeleton_archer_quiver", ixmesh_carry), ("skeleton_archer_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(60)|thrust_damage(8, pierce), imodbits_missile],
	["skeleton_archer_bow", "Bow", [("skeleton_archer_bow", 0), ("skeleton_archer_bow_c", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 17962, weight(1.25)|body_armor(32)|leg_armor(92)|difficulty(3)|spd_rtng(94)|shoot_speed(75)|thrust_damage(38, pierce), imodbits_crossbow],
	["snake_arrow", "Snake_Arrows", [("snake_arrow", 0), ("flying_missile", ixmesh_carry), ("snake_quiver", ixmesh_carry), ("snake_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 300, weight(3.25)|abundance(50)|weapon_length(95)|max_ammo(30)|thrust_damage(3, pierce), imodbits_thrown],
	["snake_arrow2", "Grey_Snake_Arrows", [("snake_arrow2", 0), ("flying_missile", ixmesh_carry), ("snake_quiver2", ixmesh_carry), ("snake_quiver2", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 300, weight(2.5)|abundance(50)|weapon_length(95)|max_ammo(24)|thrust_damage(3, pierce), imodbits_thrown],
	["snake_bow", "Snake_Bow", [("snake_bow", 0), ("snake_bow_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_cant_use_on_horseback|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 798, weight(1.75)|leg_armor(98)|difficulty(4)|spd_rtng(81)|shoot_speed(95)|thrust_damage(26, pierce), imodbits_bow],
	["snake_short_bow", "Snake_Short_Bow", [("snake_short_bow", 0), ("snake_short_bow_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 737, weight(1.25)|leg_armor(98)|difficulty(4)|spd_rtng(86)|shoot_speed(91)|thrust_damage(25, pierce), imodbits_bow],
	["spak_ar", "Arrows", [("spak_ar", 0), ("flying_missile", ixmesh_carry), ("spak_ar_bag", ixmesh_carry), ("spak_ar_bag", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 1000, weight(3.5)|weapon_length(95)|max_ammo(60)|thrust_damage(5, pierce), imodbits_missile],
	["spak_ar2", "Arrows", [("spak_ar2", 0), ("flying_missile", ixmesh_carry), ("spak_ar2bag", ixmesh_carry), ("spak_ar2bag", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["spak_arrow", "Imperial_Arrows", [("spak_arrow", 0), ("flying_missile", ixmesh_carry), ("spak_quiver", ixmesh_carry), ("spak_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["spak_bow6", "Bow", [("spak_bow6", 0), ("spak_bow6_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 1961, weight(1.25)|spd_rtng(124)|shoot_speed(98)|thrust_damage(80, pierce), imodbits_bow|imodbit_balanced|imodbit_crude],
	["spak_bow6_arrow", "Arrows", [("spak_bow6_arrow", 0), ("flying_missile", ixmesh_carry), ("spak_bow6_quiver", ixmesh_carry), ("spak_bow6_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["spak_bow7", "Bow", [("spak_bow7", 0), ("spak_bow7_case", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 1961, weight(1.25)|spd_rtng(124)|shoot_speed(98)|thrust_damage(80, pierce), imodbits_bow|imodbit_balanced|imodbit_crude],
	["spak_bow8", "Long_Bow", [("spak_bow8", 0), ("spak_bow8_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 145, weight(1.75)|difficulty(3)|spd_rtng(79)|shoot_speed(56)|thrust_damage(22, pierce), imodbits_bow],
	["spak_bow8_arrow", "Arrows", [("spak_bow8_arrow", 0), ("flying_missile", ixmesh_carry), ("spak_bow8_quiver", ixmesh_carry), ("spak_bow8_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_quiver_back, 2000, weight(3.5)|weapon_length(95)|max_ammo(30)|thrust_damage(8, pierce), imodbits_missile],
	["spak_crsb01", "Crossbow", [("spak_crsb01", 0)], itp_type_crossbow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_buckler_left|itcf_carry_crossbow_back|itcf_carry_sword_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_front_right|itcf_shoot_crossbow, 1500, weight(3.5)|leg_armor(96)|difficulty(12)|spd_rtng(35)|shoot_speed(80)|max_ammo(3)|thrust_damage(49, pierce), imodbits_crossbow],
	["spak_crsb02", "Heavy_Crossbow", [("spak_crsb02", 0)], itp_type_crossbow|itp_primary|itp_cant_reload_on_horseback|itp_two_handed|itp_merchandise, itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_buckler_left|itcf_carry_crossbow_back|itcf_carry_sword_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_front_right|itcf_shoot_crossbow, 349, weight(3.5)|leg_armor(97)|difficulty(9)|spd_rtng(41)|shoot_speed(88)|max_ammo(1)|thrust_damage(58, pierce), imodbits_crossbow],
	["voodoo_doll", "Voodoo-doll", [("voodoo-doll", 0), ("voodoo-doll_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 1961, weight(1.25)|spd_rtng(124)|shoot_speed(98)|thrust_damage(80, pierce), imodbits_bow|imodbit_balanced|imodbit_crude],
	["voodoo_needle", "Voodoo_needle", [("voodoo_needle", 0), ("voodoo_needlefl", ixmesh_carry), ("voodoo_quiver", ixmesh_carry), ("voodoo_quiver", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(20)|thrust_damage(8, pierce), imodbits_missile],
	["w_arrow", "Arrows", [("w_arr", 0), ("flying_missile", ixmesh_carry), ("w_qui", ixmesh_carry), ("w_qui", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 1000, weight(3.5)|weapon_length(95)|max_ammo(50)|thrust_damage(5, pierce), imodbits_missile],
	["bow4_spak", "Short_Bow", [("bow4_spak", 0), ("bow4_spak_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_bowcase_left|itcf_show_holster_when_drawn|itcf_carry_revolver_right|itcf_carry_pistol_front_left|itcf_carry_quiver_back|itcf_shoot_bow|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 737, weight(1.25)|leg_armor(98)|difficulty(4)|spd_rtng(86)|shoot_speed(91)|thrust_damage(25, pierce), imodbits_bow],
	["bow4_arr_spak", "Arrows", [("bow4_arr_spak", 0), ("flying_missile", ixmesh_carry), ("bow4_quiver_spak", ixmesh_carry), ("bow4_quiver_spak", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["bow3_spak", "Spak's_Bow", [("bow3_spak", 0), ("bow3_spak_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 7654, weight(2.0)|leg_armor(99)|spd_rtng(125)|shoot_speed(98)|thrust_damage(82, pierce), imodbits_bow|imodbit_balanced],
	["bow3_arr_spak", "Arrows", [("bow3_arr_spak", 0), ("flying_missile", ixmesh_carry), ("bow3_quiver_spak", ixmesh_carry), ("bow3_quiver_spak", ixmesh_carry)], itp_type_arrows|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 2000, weight(3.5)|weapon_length(95)|max_ammo(200)|thrust_damage(8, pierce), imodbits_missile],
	["bogen5", "Bow", [("bogen5", 0), ("bogen5_carry", ixmesh_carry)], itp_type_bow|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield|itcf_carry_buckler_left|itcf_shoot_bow|itcf_carry_bow_back|itcf_carry_dagger_front_right|itcf_carry_quiver_back_right, 7654, weight(2.0)|leg_armor(99)|spd_rtng(125)|shoot_speed(98)|thrust_damage(82, pierce), imodbits_bow|imodbit_balanced],
	["2imperial_warhorse", "Imperial_Warhorse", [("2imperial_warhorse", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["1lamellar_charger", "War_Horse", [("1lamellar_charger", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["2lamellar_charger", "War_Horse", [("2lamellar_charger", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["3lamellar_charger", "War_Horse", [("3lamellar_charger", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["5warhorse_holy", "War_Horse", [("5warhorse_holy", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["2charger", "Charger", [("charger2", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["charger3_new", "Charger", [("charger3_new", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["pop_empire_warbred", "Empire_Charger", [("charger4_new", 0)], itp_type_horse|itp_merchandise, 0, 1314, abundance(60)|body_armor(34)|difficulty(4)|hit_points(155)|spd_rtng(36)|shoot_speed(40)|thrust_damage(21, cut), imodbits_horse_basic|imodbit_champion],
	["eagle_on_yellow", "Falcon_Warhorse", [("eagle_on_yellow", 0)], itp_type_horse|itp_merchandise, 0, 1495, body_armor(50)|difficulty(5)|hit_points(150)|spd_rtng(35)|shoot_speed(37)|thrust_damage(22, cut), imodbits_horse_basic|imodbit_champion],
	["horny_charger_plate", "Charger", [("horny_charger_plate", 0)], itp_type_horse|itp_merchandise, 0, 2250, abundance(40)|body_armor(82)|difficulty(5)|hit_points(200)|spd_rtng(40)|shoot_speed(36)|weapon_length(112)|thrust_damage(42, cut), imodbits_horse_basic|imodbit_champion],
	["rampant_lion_red", "Lion_Warhorse", [("rampant_lion_red2", 0)], itp_type_horse|itp_merchandise, 0, 1795, body_armor(58)|difficulty(5)|hit_points(160)|spd_rtng(36)|shoot_speed(40)|thrust_damage(26, cut), imodbits_horse_basic|imodbit_champion],
	["spak_charger_plate", "Charger", [("spak_charger_plate", 0)], itp_type_horse|itp_merchandise, 0, 2250, body_armor(82)|difficulty(5)|hit_points(200)|spd_rtng(40)|shoot_speed(36)|weapon_length(112)|thrust_damage(42, cut), imodbits_horse_basic|imodbit_champion],
	["spakhorse_03", "Charger", [("spakhorse_03", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["twilight_horse", "Twilight_Charger", [("twilight_horse", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["whg", "Horse", [("whg", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["whg2", "Horse", [("whg2", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["yak1", "Yak", [("yak1", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["yak2", "Yak", [("yak2", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["yak3", "Yak", [("yak3", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["yak4", "Yak", [("yak4", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["g_horsebrown", "Horse", [("g_horsebrown", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["g_horsebrown2", "Horse", [("g_horsebrown2", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["g_horsepalomino", "Horse", [("g_horsepalomino", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["g_horsepinto", "Horse", [("g_horsepinto", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["zombi_horse", "Zombi_Horse", [("zombi_horse", 0), ("zombi_horse", imodbit_heavy|imodbit_spirited)], itp_type_horse|itp_merchandise, 0, 810, abundance(60)|body_armor(18)|difficulty(3)|hit_points(160)|spd_rtng(44)|shoot_speed(43)|weapon_length(108)|thrust_damage(24, cut), imodbits_horse_basic|imodbit_champion],
	["zombi_horse2", "Zombi_Horse", [("zombi_horse2", 0), ("zombi_horse2", imodbit_heavy|imodbit_spirited)], itp_type_horse|itp_merchandise, 0, 810, abundance(60)|body_armor(18)|difficulty(3)|hit_points(160)|spd_rtng(44)|shoot_speed(43)|weapon_length(108)|thrust_damage(24, cut), imodbits_horse_basic|imodbit_champion],
	["g_horseblack", "Horse", [("g_horseblack", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["g_horsewhite", "Horse", [("g_horsewhite", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["nibbler", "Nibbler", [("nibbler", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["riper", "Riper", [("riper", 0)], itp_type_horse|itp_merchandise, 0, 724, body_armor(85)|difficulty(4)|hit_points(185)|spd_rtng(44)|shoot_speed(39)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["heavy_riper", "Heavy_Riper", [("heavy_riper", 0)], itp_type_horse|itp_merchandise, 0, 1811, abundance(40)|body_armor(58)|difficulty(4)|hit_points(165)|spd_rtng(44)|shoot_speed(40)|weapon_length(112)|thrust_damage(32, cut), imodbits_horse_basic|imodbit_champion],
	["ripper_chain", "Ripper_Chain", [("ripper_chain", 0)], itp_type_horse|itp_merchandise, 0, 1224, abundance(50)|body_armor(40)|difficulty(4)|hit_points(165)|spd_rtng(41)|shoot_speed(40)|weapon_length(110)|thrust_damage(28, cut), imodbits_horse_basic|imodbit_champion],
	["2shield", "Shield", [("2shield", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_shield_run_alt", "Shield", [("alt_sh_run", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["asmoday_seel", "Asmoday's_Seel", [("asmoday_seel", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["heavy_shield2", "Heavy_Shield", [("heavy_shield2", 0)], itp_type_shield|itp_primary|itp_wooden_parry|itp_cant_use_on_horseback|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 1000, weight(8.5)|abundance(5)|difficulty(5)|hit_points(1100)|spd_rtng(75)|shoot_speed(70)|weapon_length(43)|swing_damage(1, cut), imodbits_shield],
	["hermitage_shield_1", "Shield", [("hermitage_shield_1", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["hermitage_shield_2", "Shield", [("hermitage_shield_2", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["hermitage_shield_3", "Shield", [("hermitage_shield_3", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["hermitage_shield_4", "Shield", [("hermitage_shield_4", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["hermitage_shield_5", "Shield", [("hermitage_shield_5", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["round_dragon_shield", "Shield", [("round_dragon_shield", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["round_dragon_shield2", "Shield", [("round_dragon_shield2", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["sh3", "Shield", [("sh3", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(18)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["sh_oval", "Bear_Shield", [("sh_oval", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(20)|hit_points(1600)|spd_rtng(100)|weapon_length(70), imodbits_none],
	["sh_snake", "Snake_Cult_Shield", [("sh_snake", 0)], itp_type_shield|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 820, weight(4.0)|body_armor(14)|hit_points(500)|spd_rtng(90)|weapon_length(44), imodbits_shield],
	["sh_spak1", "Shield", [("sh_spak1", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 340, weight(2.5)|body_armor(20)|hit_points(400)|spd_rtng(94)|shoot_speed(72)|weapon_length(42), imodbits_shield],
	["sh_spak2", "Shield", [("sh_spak2", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 340, weight(2.5)|body_armor(20)|hit_points(400)|spd_rtng(94)|shoot_speed(72)|weapon_length(42), imodbits_shield],
	["shb1", "Heater_Shield", [("shb1", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(18)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["shb2", "Shield", [("shb2", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_shield_amazon", "Shield", [("shield_amazon", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_shield_greek", "Shield", [("shield_greek", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["shield_imperial", "Shield", [("shield_imperial", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["shield_round_s3", "Shield", [("shield_round_s3", 0)], itp_type_shield|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 697, weight(4.0)|body_armor(17)|hit_points(700)|spd_rtng(61)|shoot_speed(40)|weapon_length(40), imodbits_shield],
	["sp_newsh", "Shield", [("sp_newsh", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(18)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["sp_shr1", "Twilight_Shield", [("sp_shr1", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_knight_shield", "Heater_Shield", [("spak_knight_shield", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(2)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["spak_pavise_2", "Heavy_Board_Shield", [("spak_pavise_2", 0)], itp_type_shield|itp_wooden_parry|itp_cant_use_on_horseback|itp_merchandise, itcf_carry_axe_back|itcf_carry_quiver_back|itcf_carry_board_shield, 370, weight(5.0)|body_armor(14)|hit_points(550)|spd_rtng(78)|shoot_speed(100)|weapon_length(43), imodbits_shield],
	["spak_shield_sr_3", "Shield", [("spak_shield_small_round_3", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 96, weight(2.0)|body_armor(18)|hit_points(700)|spd_rtng(105)|weapon_length(40), imodbits_shield],
	["spak_shield_wood", "Shield", [("spak_shield_wood", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_shield_wood2", "Shield", [("spak_shield_wood2", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["spak_shield_wood3", "Shield", [("spak_shield_wood3", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 196, weight(2.0)|body_armor(18)|hit_points(1600)|spd_rtng(105)|weapon_length(40), imodbit_reinforced|imodbit_lordly|imodbit_battered|imodbit_thick|imodbit_superb],
	["towershield_steel", "Tower_Shield", [("towershield_steel", 0)], itp_type_shield|itp_wooden_parry|itp_cant_use_on_horseback|itp_merchandise, itcf_carry_axe_back|itcf_carry_quiver_back|itcf_carry_board_shield, 618, weight(5.0)|body_armor(18)|hit_points(1000)|spd_rtng(84)|weapon_length(84), imodbits_shield],
	["shk_01", "Shield", [("shk_01", 0)], itp_type_shield|itp_primary|itp_wooden_parry, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 150, weight(3.0)|body_armor(14)|hit_points(350)|spd_rtng(98)|weapon_length(55), imodbits_shield],
	["cheap_pavise", "Cheap_Pavise", [("g_pavise_01", 0)], itp_type_shield|itp_primary|itp_wooden_parry|itp_cant_use_on_horseback|itp_merchandise, itcf_carry_axe_back|itcf_carry_quiver_back|itcf_carry_board_shield, 100, weight(5.0)|abundance(20)|head_armor(10)|difficulty(3)|hit_points(200)|spd_rtng(83)|shoot_speed(104)|weapon_length(43), imodbits_shield],
	["g_shield_10", "Strange_Shield", [("g_shield_10", 0)], itp_type_shield|itp_primary|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 420, weight(2.5)|body_armor(18)|hit_points(350)|spd_rtng(95)|weapon_length(40), imodbits_shield|imodbit_lordly],
	["spider_shield2", "Spider_Shield", [("spider_shield2", 0)], itp_type_shield|itp_primary|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 100, weight(2.0)|body_armor(18)|hit_points(350)|spd_rtng(98)|weapon_length(40), imodbits_shield|imodbit_lordly],
	["spikeshield_01", "Shield", [("spikeshield_01", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(18)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["spikeshield_02", "Shield", [("spikeshield_02", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 277, weight(3.5)|body_armor(18)|hit_points(410)|spd_rtng(80)|weapon_length(50), imodbits_shield],
	["dargor_shield", "Dargor_Shield", [("dargor_shield", 0)], itp_type_shield|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_kite_shield, 336, weight(2.0)|body_armor(20)|hit_points(400)|spd_rtng(96)|shoot_speed(70)|weapon_length(42), imodbit_reinforced|imodbit_lordly|imodbit_thick],
	["sub_shield_01", "Shield", [("sub_shield_01", 0)], itp_type_shield|itp_primary|itp_wooden_parry|itp_merchandise, itcf_carry_axe_left_hip|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_kite_shield|itcf_carry_round_shield|itcf_carry_sword_left_hip|itcf_carry_dagger_front_left, 100, weight(2.0)|body_armor(18)|hit_points(350)|spd_rtng(98)|weapon_length(40), imodbits_shield|imodbit_lordly],
	["spak_2h_battle_axe", "Two_Handed_Axe", [("spak_2h_battle_axe", 0)], itp_type_two_handed_wpn|itp_primary|itp_unbalanced|itp_wooden_parry|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itc_nodachi|itcf_carry_axe_back, 90, weight(4.5)|difficulty(10)|hit_points(38912)|spd_rtng(96)|weapon_length(90)|thrust_damage(0, pierce)|swing_damage(38, cut), imodbits_mace],
	["2double_axe", "Double_Axe", [("2dblhead_ax", 0)], itp_type_two_handed_wpn|itp_primary|itp_wooden_parry|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itc_nodachi|itcf_carry_axe_back|itcf_overswing_onehanded|itcf_thrust_twohanded, 357, weight(6.5)|difficulty(12)|hit_points(47104)|spd_rtng(85)|weapon_length(95)|thrust_damage(20, pierce)|swing_damage(46, cut), imodbits_pick],
	["asmoday_sword", "Asmoday's_Sword", [("asmoday_sword", 0), ("asmoday_sword_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(100)|weapon_length(115)|thrust_damage(60, pierce)|swing_damage(60, pierce), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["butcher", "Butcher", [("butcher", 0), ("butcher_scab", ixmesh_carry)], itp_type_one_handed_wpn|itp_primary|itp_merchandise|itp_next_item_as_melee, itc_longsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_carry_sword_left_hip, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(90)|weapon_length(110)|thrust_damage(50, pierce)|swing_damage(80, cut), imodbit_balanced|imodbit_rusty|imodbit_masterwork|imodbit_tempered],
	["2butcher", "Butcher", [("butcher", 0), ("butcher_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_unbalanced|itp_bonus_against_shield|itp_two_handed, itc_parry_two_handed|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(110)|weapon_length(110)|thrust_damage(80, pierce)|swing_damage(120, pierce), imodbit_balanced|imodbit_rusty|imodbit_masterwork|imodbit_tempered],
	["dargor_axe", "Dargor's_Axe", [("dargor_axe", 0)], itp_type_two_handed_wpn|itp_primary|itp_wooden_parry|itp_two_handed|itp_merchandise, itc_nodachi|itcf_carry_axe_back|itcf_thrust_twohanded, 946, weight(4.0)|difficulty(10)|hit_points(56320)|spd_rtng(95)|weapon_length(96)|thrust_damage(0, pierce)|swing_damage(55, cut), imodbits_pick],
	["demon_sword", "Sword", [("demon_sword", 0), ("demon_sword_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(100)|weapon_length(115)|thrust_damage(60, pierce)|swing_damage(60, pierce), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["flamberg", "Flamberg", [("flamberg", 0)], itp_type_two_handed_wpn|itp_always_loot|itp_primary|itp_bonus_against_shield|itp_two_handed|itp_merchandise, itcf_carry_axe_back|itcf_carry_sword_back|itcf_horseback_slashright_onehanded|itcf_horseback_slashleft_onehanded|itcf_overswing_twohanded|itcf_parry_forward_twohanded|itcf_parry_up_twohanded|itcf_parry_right_twohanded|itcf_slashleft_twohanded|itcf_parry_left_twohanded|itcf_carry_sword_left_hip|itcf_thrust_onehanded_lance|itcf_slashright_twohanded|itcf_thrust_twohanded, 1123, weight(2.75)|difficulty(10)|hit_points(43008)|spd_rtng(89)|weapon_length(120)|thrust_damage(38, pierce)|swing_damage(62, cut), imodbits_sword_high],
	["flat_sword", "Fury_Sword", [("flat_sword", 0)], itp_type_two_handed_wpn|itp_primary|itp_wooden_parry|itp_two_handed, itc_greatsword|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_sword_left_hip, 2964, weight(7.0)|abundance(1)|difficulty(8)|hit_points(45056)|spd_rtng(90)|weapon_length(109)|thrust_damage(3, pierce)|swing_damage(44, cut), imodbits_sword_high],
	["hookSword_spak", "Hooked_Sword", [("hookSword_spak", 0), ("hookSword_spak_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_show_holster_when_drawn|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(100)|weapon_length(115)|thrust_damage(35, pierce)|swing_damage(50, pierce), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["kingslayer", "Kingslayer", [("kingslayer", 0), ("kingslayer_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(100)|weapon_length(115)|thrust_damage(35, pierce)|swing_damage(50, pierce), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["lightedge_spak", "Light_Edge", [("lightedge_spak", 0)], itp_type_two_handed_wpn|itp_primary|itp_unbalanced|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_carry_axe_back|itcf_carry_sword_back|itcf_thrust_onehanded_lance_horseback|itcf_horseback_overswing_left_onehanded|itcf_overswing_twohanded|itcf_horseback_thrust_onehanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_thrust_onehanded_lance|itcf_slashright_twohanded|itcf_horseback_overswing_right_onehanded|itcf_thrust_twohanded, 660, weight(5.0)|difficulty(12)|hit_points(51200)|spd_rtng(88)|weapon_length(155)|thrust_damage(17, pierce)|swing_damage(50, cut), imodbits_mace|imodbit_masterwork],
	["pickaxe", "Pickaxe", [("pickaxe", 0)], itp_type_two_handed_wpn|itp_primary|itp_wooden_parry|itp_merchandise, itc_morningstar|itcf_carry_axe_back|itcf_carry_sword_back|itcf_carry_sword_left_hip, 350, weight(2.5)|hit_points(35840)|spd_rtng(97)|weapon_length(67)|thrust_damage(0, pierce)|swing_damage(35, pierce), imodbits_pick],
	["pickaxe_hand", "Deadly_Hand", [("pickaxe_hand", 0)], itp_type_one_handed_wpn|itp_primary|itp_wooden_parry|itp_merchandise, itc_scimitar|itcf_carry_axe_left_hip, 108, weight(1.5)|hit_points(25600)|spd_rtng(98)|weapon_length(67)|thrust_damage(0, pierce)|swing_damage(25, pierce), imodbits_pick],
	["s_sword", "Sword", [("s_sword", 0), ("s_sword_scab", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_bonus_against_shield|itp_merchandise, itc_longsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_overswing_twohanded|itcf_slashleft_twohanded|itcf_carry_sword_left_hip|itcf_slashright_twohanded|itcf_thrust_twohanded, 1803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(100)|weapon_length(115)|thrust_damage(35, pierce)|swing_damage(50, pierce), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["sp_2hsw", "Sword", [("sp_2hsw", 0), ("sp_2hsw_sh", ixmesh_carry)], itp_type_two_handed_wpn|itp_primary|itp_two_handed|itp_merchandise, itc_greatsword|itcf_carry_axe_back|itcf_show_holster_when_drawn|itcf_carry_sword_back|itcf_carry_sword_left_hip, 803, weight(1.0)|difficulty(8)|hit_points(37888)|spd_rtng(95)|weapon_length(115)|thrust_damage(40, pierce)|swing_damage(50, cut), imodbit_balanced|imodbit_masterwork|imodbit_tempered],
	["spak_IceAxe", "Axe", [("spak_IceAxe", 0)], itp_type_two_handed_wpn|itp_primary|itp_wooden_parry|itp_bonus_against_shield|itp_merchandise, itc_bastardsword|itcf_carry_axe_back|itcf_horseback_overswing_left_onehanded|itcf_horseback_thrust_onehanded|itcf_horseback_overswing_right_onehanded, 946, weight(4.0)|difficulty(10)|hit_points(56320)|spd_rtng(95)|weapon_length(96)|thrust_damage(50, pierce)|swing_damage(55, cut), imodbits_pick]]